version: "3"
services:
    nginx:
      container_name: nginx
      image: nginx:stable
      ports:
        - "7070:80"
      volumes:
        #- ./laravel:/var/www/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    php:
      container_name: php
      build:
        context: php
        dockerfile: Dockerfile
      volumes:
        - ./code:/var/www/
      ports:
        - "9000:9000"
    mysql:
      container_name: mysql
      image: mysql:8.0.29-oracle
      ports:
        - "3307:3306"
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        MYSQL_DATABASE: laravel_test
        MYSQL_USER: tinh
        MYSQL_PASSWORD: tinh123
        MYSQL_ROOT_PASSWORD: root123
    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin
      ports:
        - "8081:80"
      environment:
        - PMA_HOSTS=mysql
        - PMA_PORT=3307
        - PMA_USER=pocadi
        - PMA_PASSWORD=pocadi123