version: "3"
services:
    php:
      container_name: php
      build:
        context: php
        dockerfile: Dockerfile
      volumes:
        - ./code:/var/www/
      ports:
        - "9000:9000"
